tasks:
  - before: pip3 install -U platformio
    command: platformio run -e heltec_wifi_lora_32_V2
vscode:
  extensions:
    - platformio.platformio-ide@1.10.0:aIt2v3YhW3veGlO/Uthh3Q==
    - ms-vscode.cpptools@0.28.0:3bMoEAAzdrP+gtq/4qm44Q==